use_frameworks!

platform :ios, '14.0'

target 'ios-location-listener_Example' do
  pod 'ios-location-listener', :path => '../'

  target 'ios-location-listener_Tests' do
    inherit! :search_paths


  end
end
